feat(scripts): Updated syntax for shellcheck

diff --git a/scripts/genpkglist b/scripts/genpkglist
--- a/scripts/genpkglist
+++ b/scripts/genpkglist
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # Source for all list generating commands:
 # https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#List_of_installed_packages
@@ -8,50 +8,49 @@ logFile="/home/${user}/.dotfiles/scripts/genpkglist.log"
 logTime="$(date --rfc-3339="seconds")"
 pkgListDir="/home/${user}/.dotfiles/pkglists"
 
-function setupListings () {
-    local creationTime
-    creationTime="$(date '+%F')"
+function setupListings() {
+	local creationTime
+	local currentList
+	local logMessage
+	creationTime="$(date '+%F')"
 
-    for source in "$@";
-    do
-        local currentList
-        local logMessage
-        currentList="${pkgListDir}/${source}-${creationTime}.txt"
-        logMessage="[${logTime}] ${source} install listing: ${currentList}"
+	for source in "$@"; do
+		currentList="${pkgListDir}/${source}-${creationTime}.txt"
+		logMessage="[${logTime}] ${source} install listing: ${currentList}"
 
-        case "${source}" in
-            AUR)
-                pacman -Qqem > ${currentList} 
-                ;;
+		case "${source}" in
+		AUR)
+			pacman -Qqem >"${currentList}"
+			;;
 
-            Flatpak)
-                flatpak list --columns=application --app > ${currentList} 
-                ;;
+		Flatpak)
+			flatpak list --columns=application --app >"${currentList}"
+			;;
 
-            Optional)
-                comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort) > ${currentList} 
-                ;;
+		Optional)
+			comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort) >"${currentList}"
+			;;
 
-            Explicit)
-                pacman -Qqen > ${currentList} 
-                ;;
+		Explicit)
+			pacman -Qqen >"${currentList}"
+			;;
 
-            *)
-                echo "[${logTime}] Error: $1 undefined as a source." >> ${logFile}
-                exit 1
-                ;;
-        esac
+		*)
+			echo "[${logTime}] Error: $1 undefined as a source." >>"${logFile}"
+			exit 1
+			;;
+		esac
 
-        echo "${logMessage}" >> ${logFile}
-    done
+		echo "${logMessage}" >>"${logFile}"
+	done
 }
 
 if [[ -e "${pkgListDir}" ]]; then
-    rm -rf "${pkgListDir}"
-    echo "[${logTime}] Cleared previous package lists under ${pkgListDir}" >> ${logFile}
+	rm -rf "${pkgListDir}"
+	echo "[${logTime}] Cleared previous package lists under ${pkgListDir}" >>"${logFile}"
 fi
 
 mkdir "${pkgListDir}"
-echo "[${logTime}] New package listing master directory: ${pkgListDir}" >> ${logFile}
+echo "[${logTime}] New package listing master directory: ${pkgListDir}" >>"${logFile}"
 
 setupListings "AUR" "Flatpak" "Optional" "Explicit"
